#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# prezto ovverides
alias rm='rm'

# Set additional directories for functions
fpath=(
  $HOME/.zsh/functions
  $fpath
)

autoload -Uz term_colors

# Macvim
if [[ "$OSTYPE" == darwin* ]]
then
  alias vim="/Applications/MacVim.app/Contents/MacOS/Vim"
fi

alias hastier="cat $1 | haste | pbcopy"
alias mman="middleman"

echo "Did you update your system today?"
